global-settings:
  enabled: true
  allowed-commands: /list, /pl, /msg
  update-notification: true
  prefix: '&a[MobArena] '
  pet-items:
    wolf: bone
classes:
  Knight:
    items: diamond_sword, 373:8197:3
    armor: iron_helmet, iron_chestplate, iron_leggings, iron_boots
  Tank:
    items: iron_sword, potion:instant_heal:2
    armor: diamond_helmet, diamond_chestplate, diamond_leggings, diamond_boots
    effects: slow, health_boost
  Archer:
    items: wood_sword, bow, arrow:256, potion:instant_heal:3, bone
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
    effects: speed
  Chemist:
    items: stone_sword, splash_potion:instant_damage:30, splash_potion:poison:8, splash_potion:instant_heal:20, potion:instant_heal:3
    armor: chainmail_helmet, chainmail_chestplate, chainmail_leggings, chainmail_boots
    effects: speed:1
  Oddjob:
    items: stone_sword, flint_and_steel, tnt:4, potion:instant_heal:3
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
arenas:
  Redemption:
    settings:
      prefix: ''
      world: Redemption
      enabled: true
      protect: true
      entry-fee: ''
      default-class: ''
      clear-wave-before-next: true
      clear-boss-before-next: true
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      share-items-in-arena: false
      min-players: 0
      max-players: 0
      max-join-distance: 0
      join-interrupt-timer: 0
      first-wave-delay: 10
      next-wave-delay: 0
      wave-interval: 15
      final-wave: 100
      monster-limit: 100
      monster-exp: false
      keep-exp: false
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: true
      auto-start-timer: 300
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      boss-health-bar: title
      display-waves-as-level: true
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: true
      global-join-announce: true
      global-end-announce: true
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 6
            spiders: 8
            creepers: 4
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered_creepers: 5
            zombie_pigmen: 9
            angry_wolves: 10
            blazes: 8
            witches: 5
            baby_pigmen: 8
            silverfish: 10
            cave_spiders: 10
            exploding_sheep: 7
        sup1:
          type: supply
          priority: 3
          frequency: 5
          monsters:
            zombie: 10
            baby_zombie: 5
          drops: ender_pearl, golden_apple, tnt:3,
      single:
        up1:
          type: upgrade
          wave: 11
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up2:
          type: upgrade
          wave: 21
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up3:
          type: upgrade
          wave: 31
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up4:
          type: upgrade
          wave: 41
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up5:
          type: upgrade
          wave: 51
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up6:
          type: upgrade
          wave: 61
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up7:
          type: upgrade
          wave: 71
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up8:
          type: upgrade
          wave: 81
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: true
        up9:
          type: upgrade
          wave: 91
          upgrades:
            Knight:
              armor: diamond_boots
          give-all-items: false
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        swarm2:
          type: swarm
          wave: 16
          monster: magmacube
          amount: low
        swarm3:
          type: swarm
          wave: 26
          monster: silverfish
          amount: low
        swarm4:
          type: swarm
          wave: 36
          monster: angry_wolf
          amount: medium
        swarm5:
          type: swarm
          wave: 46
          monster: cave_spider
          amount: medium
        swarm6:
          type: swarm
          wave: 56
          monster: baby_pigman
          amount: medium
        swarm7:
          type: swarm
          wave: 66
          monster: wither_skeleton
          amount: high
        swarm8:
          type: swarm
          wave: 76
          monster: exploding_sheep
          amount: high
        swarm9:
          type: swarm
          wave: 86
          monster: witch
          amount: high
        swarm10:
          type: swarm
          wave: 96
          monster: iron_golem
          amount: psycho
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          name: Creepy Crawly
          health: verylow
          abilities: arrows, root-target, pull-nearby
          ability-interval: 5
        boss2:
          type: boss
          wave: 20
          monster: enderman
          name: Teleporting Terror
          health: verylow
          abilities: arrows, shuffle-positions, warp-to-player, fetch-nearby, fetch-distant
          ability-interval: 5
        boss3:
          type: boss
          wave: 30
          monster: angry_wolf
          name: Pushy Predator
          health: low
          abilities: arrows, throw-target, throw-distant, throw-nearby
          ability-interval: 5
        boss4:
          type: boss
          wave: 40
          monster: blaze
          name: Fire Mage
          health: low
          abilities: arrows, fireballs, fire_aura
          ability-interval: 4
        boss5:
          type: boss
          wave: 50
          monster: zombie_pigman
          name: Weather Maniac
          health: medium
          abilities: arrows, lightning-aura, chain-lightning
          ability-interval: 7
        boss6:
          type: boss
          wave: 60
          monster: wither_skeleton
          name: Stranger Danger
          health: medium
          abilities: arrows, pull-target, pull-nearby, pull-distant, fetch-target
          ability-interval: 5
        boss7:
          type: boss
          wave: 70
          monster: enderman
          name: Teleporting Terror Sr.
          health: high
          abilities: arrows, fetch-target, shuffle-positions, fetch-nearby, warp-to-player, fetch-distant
          ability-interval: 5
        boss8:
          type: boss
          wave: 80
          monster: silverfish
          name: The Confuser
          health: high
          abilities: arrows, disorient-target, shuffle-positions, disorient-nearby, disorient-distant
          ability-interval: 4
        boss9:
          type: boss
          wave: 90
          monster: creeper
          name: The Prince
          health: veryhigh
          abilities: arrows, fire-aura, chain-lightning, disorient-nearby, warp-to-player, pull-distant, lightning-aura, obsidian-bomb
          ability-interval: 4
        boss10:
          type: boss
          wave: 100
          monster: iron_golem
          name: The King
          health: psycho
          abilities: arrows, fireballs, fire-aura, disorient-nearby, disorient-distant, chain-lightning, root-target, throw-nearby, throw-distant, shuffle-positions, obsidian-bomb, living-bomb, fetch-target
          ability-interval: 3
    rewards:
      waves:
        every:
          '3': feather, bone, stick
          '5': dirt:4, gravel:4, stone:4
          '10': iron_ingot:10, gold_ingot:8
        after:
          '7': minecart, storage_minecart, powered_minecart
          '13': iron_sword, iron_pickaxe, iron_spade
          '16': diamond_sword
    coords:
      spawnpoints:
        20,56,-167: 20.5,56,-166.5,0.0,0.0,Redemption
        47,56,-167: 47.5,56,-166.5,0.0,0.0,Redemption
        47,56,-193: 47.5,56,-192.5,0.0,0.0,Redemption
        20,56,-193: 20.5,56,-192.5,0.0,0.0,Redemption
        33,59,-111: 33.5,59,-110.5,0.0,0.0,Redemption
        24,57,-141: 24.5,57,-140.5,0.0,0.0,Redemption
        43,57,-141: 43.5,57,-140.5,0.0,0.0,Redemption
      containers: {}
      l1: -53,55,-154,0.0,0.0,Redemption
      l2: -28,61,-137,0.0,0.0,Redemption
      p1: 6,55,-206,0.0,0.0,Redemption
      p2: 61,66,-99,0.0,0.0,Redemption
      spectator: 34.5,62,-106.5,180.33,0.0,Redemption
      arena: 34.5,61,-108.5,348.39,0.0,Redemption
      lobby: -35.5,56,-145.5,-91.36,0.0,Redemption
    class-limits:
      Oddjob: -1
      Knight: -1
      Archer: -1
      My Items: -1
      Tank: -1
      Chemist: -1
