global-settings:
  enabled: true
  allowed-commands: /list, /pl, /msg
  update-notification: true
  prefix: '&a[MobArena] '
  pet-items:
    wolf: bone
classes:
  Knight:
    items: diamond_sword, potion:instant_heal:3
    armor: iron_helmet, iron_chestplate, iron_leggings, iron_boots
    unbreakable-weapons: true
    unbreakable-armor: true
  Tank:
    items: iron_sword, potion:instant_heal:2
    armor: diamond_helmet, diamond_chestplate, diamond_leggings, diamond_boots
    effects: slow, health_boost
    unbreakable-weapons: true
    unbreakable-armor: true
  Archer:
    items: wood_sword, bow, arrow:256, potion:instant_heal:3, bone
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
    effects: speed
    unbreakable-weapons: true
    unbreakable-armor: true
  Chemist:
    items: stone_sword, splash_potion:instant_heal:30, splash_potion:poison:8, splash_potion:instant_damage:20, potion:instant_heal:3
    armor: chainmail_helmet, chainmail_chestplate, chainmail_leggings, chainmail_boots
    effects: speed:1
    unbreakable-weapons: true
    unbreakable-armor: true
  Oddjob:
    items: stone_sword, flint_and_steel, tnt:4, potion:instant_heal:3
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
    unbreakable-weapons: true
    unbreakable-armor: true
arenas:
  Redemption:
    settings:
      prefix: ''
      world: Redemption
      enabled: true
      protect: true
      entry-fee: ''
      default-class: ''
      clear-wave-before-next: true
      clear-boss-before-next: true
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      share-items-in-arena: false
      min-players: 0
      max-players: 0
      max-join-distance: 0
      join-interrupt-timer: 0
      first-wave-delay: 10
      next-wave-delay: 0
      wave-interval: 15
      final-wave: 100
      monster-limit: 100
      monster-exp: false
      keep-exp: false
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 300
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      boss-health-bar: name
      display-waves-as-level: true
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: true
      global-join-announce: true
      global-end-announce: true
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 6
            spiders: 8
            creepers: 4
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered_creepers: 5
            zombie_pigmen: 9
            angry_wolves: 10
            blazes: 8
            witches: 5
            baby_pigmen: 8
            silverfish: 10
            cave_spiders: 10
            exploding_sheep: 7
        sup1:
          type: supply
          priority: 3
          frequency: 5
          monsters:
            zombie: 10
            baby_zombie: 5
          drops: ender_pearl, golden_apple
      single:
        up1:
          type: upgrade
          wave: 11
          upgrades:
            all:
              effects: regeneration:0:30
            Knight:
              armor: diamond_boots
              items: diamond_sword 17:1
          give-all-items: true
        up2:
          type: upgrade
          wave: 21
          upgrades:
            all:
              effects: regeneration:0:30
              items: golden_apple
            Knight:
              armor: diamond_helmet
              items: diamond_sword 17:1;19:1
          give-all-items: true
        up3:
          type: upgrade
          wave: 31
          upgrades:
            all:
              effects: regeneration:0:30
            Knight:
              armor: diamond_leggings, diamond_boots 0:1
              items: diamond_sword 17:2;19:1
          give-all-items: true
        up4:
          type: upgrade
          wave: 41
          upgrades:
            all:
              effects: regeneration:0:30
              items: golden_apple
            Knight:
              armor: diamond_chestplate, diamond_helmet 0:1
              items: diamond_sword 17:2;19:1;20:1
          give-all-items: true
        up5:
          type: upgrade
          wave: 51
          upgrades:
            all:
              effects: regeneration:0:30
            Knight:
              armor: diamond_leggings 0:1
              items: diamond_sword 16:1;17:3;19:1;20:1
          give-all-items: true
        up6:
          type: upgrade
          wave: 61
          upgrades:
            all:
              effects: regeneration:0:30
              items: golden_apple
            Knight:
              armor: diamond_chestplate 0:1
              items: diamond_sword 16:1;17:3;18:1;19:1;20:1
          give-all-items: true
        up7:
          type: upgrade
          wave: 71
          upgrades:
            all:
              effects: regeneration:0:30
            Knight:
              armor: diamond_helmet 0:1;7:1, diamond_boots 0:1;7:1
              items: diamond_sword 16:2;17:3;18:1;19:1;20:2
          give-all-items: true
        up8:
          type: upgrade
          wave: 81
          upgrades:
            all:
              effects: regeneration:0:30
              items: golden_apple:2
            Knight:
              armor: diamond_leggings 0:1;7:1, diamond_chestplate 0:1;7:1, diamond_boots 0:2;7:1
              items: diamond_sword 16:3;17:3;18:2;19:1;20:2
          give-all-items: true
        up9:
          type: upgrade
          wave: 91
          upgrades:
            all:
              effects: regeneration:0:30
              items: golden_apple:3
            Knight:
              armor: diamond_helmet 0:2;7:1, diamond_leggings 0:2;7:1, diamond_chestplate 0:2;7:1
              items: diamond_sword 16:4;17:3;18:3;19:2;20:2
          give-all-items: true
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        swarm2:
          type: swarm
          wave: 16
          monster: magmacube
          amount: low
        swarm3:
          type: swarm
          wave: 26
          monster: silverfish
          amount: low
        swarm4:
          type: swarm
          wave: 36
          monster: angry_wolf
          amount: medium
        swarm5:
          type: swarm
          wave: 46
          monster: cave_spider
          amount: medium
        swarm6:
          type: swarm
          wave: 56
          monster: baby_pigman
          amount: medium
        swarm7:
          type: swarm
          wave: 66
          monster: wither_skeleton
          amount: high
        swarm8:
          type: swarm
          wave: 76
          monster: exploding_sheep
          amount: high
        swarm9:
          type: swarm
          wave: 86
          monster: witch
          amount: high
        swarm10:
          type: swarm
          wave: 96
          monster: iron_golem
          amount: psycho
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          name: Creepy Crawly
          health: verylow
          abilities: arrows, root-target, pull-nearby
          ability-interval: 5
        boss2:
          type: boss
          wave: 20
          monster: enderman
          name: Teleporting Terror
          health: verylow
          abilities: arrows, shuffle-positions, warp-to-player, fetch-nearby, fetch-distant
          ability-interval: 5
        boss3:
          type: boss
          wave: 30
          monster: angry_wolf
          name: Pushy Predator
          health: low
          abilities: arrows, throw-target, throw-distant, throw-nearby
          ability-interval: 5
        boss4:
          type: boss
          wave: 40
          monster: blaze
          name: Fire Mage
          health: low
          abilities: arrows, fireballs, fire_aura
          ability-interval: 4
        boss5:
          type: boss
          wave: 50
          monster: zombie_pigman
          name: Weather Maniac
          health: medium
          abilities: arrows, lightning-aura, chain-lightning
          ability-interval: 7
        boss6:
          type: boss
          wave: 60
          monster: wither_skeleton
          name: Stranger Danger
          health: medium
          abilities: arrows, pull-target, pull-nearby, pull-distant, fetch-target
          ability-interval: 5
        boss7:
          type: boss
          wave: 70
          monster: enderman
          name: Teleporting Terror Sr.
          health: high
          abilities: arrows, fetch-target, shuffle-positions, fetch-nearby, warp-to-player, fetch-distant
          ability-interval: 5
        boss8:
          type: boss
          wave: 80
          monster: silverfish
          name: The Confuser
          health: high
          abilities: arrows, disorient-target, shuffle-positions, disorient-nearby, disorient-distant
          ability-interval: 4
        boss9:
          type: boss
          wave: 90
          monster: creeper
          name: The Prince
          health: veryhigh
          abilities: arrows, fire-aura, chain-lightning, disorient-nearby, warp-to-player, pull-distant, lightning-aura, obsidian-bomb
          ability-interval: 4
        boss10:
          type: boss
          wave: 100
          monster: iron_golem
          name: The King
          health: psycho
          abilities: arrows, fireballs, fire-aura, disorient-nearby, disorient-distant, chain-lightning, root-target, throw-nearby, throw-distant, shuffle-positions, obsidian-bomb, living-bomb, fetch-target
          ability-interval: 3
    rewards:
      waves:
        every:
          '3': stick, stick, stick:2, stick:2, stick:3, bone, bone, bone:2, feather, feather, feather:2, seeds, seeds, seeds:2, seeds:2, seeds:3, string, string, string:2, sulphur, sulphur, wood, wood, furnace, chest
          '5': clay_ball, clay_ball, clay_ball:2, clay_ball:2, clay_ball:3, melon_seeds, melon_seeds, melon_seeds:2, melon_seeds:2, coal, coal, coal:2, coal:2, coal:3, pork, pork:2, wool, wool:2, leather, leather:2, arrow, slime_ball, gold_ingot, iron_ingot
        after:
          '10': chainmail_helmet, chainmail_chestplate, chainmail_leggings, chainmail_boots, stone_sword, stone_pickaxe, golden_hoe, apple:3, apple:4, apple:5
          '20': blaze_powder, cooked_beef:2, cooked_beef:3, iron_pickaxe, tnt:2, tnt:3, bow, fire_charge, minecart
          '30': iron_sword, iron_sword 16:1, iron_sword 17:2, bow 48:1, diamond, bookshelf
          '40': enchanted_book 50:1, enchanted_book 32:1, enchanted_book 32:2, iron_helmet, iron_helmet 3:1, iron_chestplate
          '50': emerald, golden_apple, diamond_leggings, diamond_boots, diamond_boots 2:1
          '60': enchantment_table, cake:2, cake:3, obsidian:3, obsidian:4, obsidian:5, arrow:32
          '70': golden_apple:3, experience_bottle:32, diamond_chestplate 0:1, diamond_helmet 0:1;7:1, bow 51:1
          '80': tnt:64, enchanted_golden_apple:1, diamond_pickaxe 34:2;32:2;35:1, nether_star
          '90': ender_chest, diamond_leggings 0:3;34:2;7:2, enchanted_book 20:2, melon_block:64
          '100': enchanted_book 16:5, enchanted_book 0:4, enchanted_book 48:5, diamond_sword 16:3;19:1;20:1;21:2;34:3, enchanted_golden_apple:3
    coords:
      spawnpoints:
        20,56,-167: 20.5,56,-166.5,0.0,0.0,Redemption
        47,56,-167: 47.5,56,-166.5,0.0,0.0,Redemption
        47,56,-193: 47.5,56,-192.5,0.0,0.0,Redemption
        20,56,-193: 20.5,56,-192.5,0.0,0.0,Redemption
        33,59,-111: 33.5,59,-110.5,0.0,0.0,Redemption
        24,57,-141: 24.5,57,-140.5,0.0,0.0,Redemption
        43,57,-141: 43.5,57,-140.5,0.0,0.0,Redemption
      containers: {}
      l1: -53,55,-154,0.0,0.0,Redemption
      l2: -28,61,-137,0.0,0.0,Redemption
      p1: 6,55,-206,0.0,0.0,Redemption
      p2: 61,66,-99,0.0,0.0,Redemption
      spectator: 34.5,62,-106.5,180.33,0.0,Redemption
      arena: 34.5,61,-108.5,348.39,0.0,Redemption
      lobby: -35.5,56,-145.5,-91.36,0.0,Redemption
    class-limits:
      Oddjob: -1
      Knight: -1
      Archer: -1
      My Items: -1
      Tank: -1
      Chemist: -1
